server:
  port: ${SERVER_PORT:8081}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/taskrunner}

runner:
  namespace: ${RUNNER_NAMESPACE:task-runner}
  jobTimeoutSeconds: ${RUNNER_JOB_TIMEOUT_SECONDS:60}
  image: ${RUNNER_IMAGE:alpine:3.19}

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]

app:
  cors:
    allowedOrigin: ${FRONTEND_ORIGIN:http://localhost:5173}
